lang: default
title: Space Invaders
start: Mission Start
close: Close
top_message: Space Invaders PLUS
initial_message: Help us, awesome captain !! <br> The aliens are trying to invade our planet.<br> <br> <br> Your mission:<br> <br> Kill all invading aliens before they can invade planet Earth.<br> And, preferably, don't die during the battle!<br> <br> <br> GOOD LUCK !!!
help_top_message: Help
help_message: Controls:<br> <br> Move Left: <br> Left Arrow on Keyboard<br> <br> Right Movement: <br> Right Arrow on Keyboard<br> <br> Shoot: <br> Spacebar
ending_win: Congratulations! You saved the galaxy!
ending_lose: Your planet belongs to us now ...
invade: Aliens are invading the galaxy!
language_selection: Language Selection